### ISSUE TITLE
GMM Pickles

### ISSUE THREAD

**Issue by torridgristle** [genforce/fairgen#1]
How do I go about making these GMM files for attributes and models of my own?

**Comment by Ariostgx** [comment]
Basically, we follow the following steps:

1. Find the manipulation directions in the latent space for the semantic attributes (e.g., age, eyeglasses). One way to do this is using [https://github.com/genforce/interfacegan](url)).

2. Use the directions you found in the first step to create latent codes specifically for each semantic attribute subgroup (e.g., young people with eyeglasses).

3. Use the GMM model in sklearn to fit the created latent codes in each of the subgroups. Then, we get the GMM models that can produce latent codes for different sementic subgroups.
