### ISSUE TITLE
How did you fit the GMM with stylegan weight latent

### ISSUE THREAD

**Issue by EricWang12** [genforce/fairgen#4]
Hi,
great work,
I am confused about how you fit the GMM, according to the paper you used the weight w instead of latent z as the latent vector. The weight has 14x512 dimensions, which is a lot for a GMM model. Did you use any ways to reduce that? How did you fit the GMM with that?

Thanks!

**Comment by Ariostgx** [comment]
That's a good point! Actually the latent codes w we are fitting to are still in 1x512 dimensions, which is the output of the fc mapping network in Figure 1(b) of the StyleGAN paper (https://arxiv.org/pdf/1812.04948.pdf).
